name: bookstore_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  logger: ^2.0.2+1
  device_preview: ^1.2.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  fluttertoast: ^8.2.2
  intl: ^0.19.0
  flutter_stripe: ^11.5.0
  http: ^1.2.0
  sqflite: ^2.3.3
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
