// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        /* throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        ); */
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB_Ivg14RdoOPiifwGzeawOhqJo_9YUHw',
    appId: '1:754175928853:web:00cfa40365bbfd2cdf3c1c',
    messagingSenderId: '754175928853',
    projectId: 'bookstore-app-28217',
    authDomain: 'bookstore-app-28217.firebaseapp.com',
    storageBucket: 'bookstore-app-28217.firebasestorage.app',
    measurementId: 'G-N2MM9PJVXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZsgA8c7ner-sZnxFnN22boad_Xcf-5K4',
    appId: '1:754175928853:android:54ce7aeddf1cdcacdf3c1c',
    messagingSenderId: '754175928853',
    projectId: 'bookstore-app-28217',
    storageBucket: 'bookstore-app-28217.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK5Amj6UDoqSFcoG6jJas_8oZTM1UDSsI',
    appId: '1:754175928853:ios:4d77b4ad954d4dffdf3c1c',
    messagingSenderId: '754175928853',
    projectId: 'bookstore-app-28217',
    storageBucket: 'bookstore-app-28217.firebasestorage.app',
    iosBundleId: 'com.example.bookstoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK5Amj6UDoqSFcoG6jJas_8oZTM1UDSsI',
    appId: '1:754175928853:ios:4d77b4ad954d4dffdf3c1c',
    messagingSenderId: '754175928853',
    projectId: 'bookstore-app-28217',
    storageBucket: 'bookstore-app-28217.firebasestorage.app',
    iosBundleId: 'com.example.bookstoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB_Ivg14RdoOPiifwGzeawOhqJo_9YUHw',
    appId: '1:754175928853:web:ea2a4cf8d08acefedf3c1c',
    messagingSenderId: '754175928853',
    projectId: 'bookstore-app-28217',
    authDomain: 'bookstore-app-28217.firebaseapp.com',
    storageBucket: 'bookstore-app-28217.firebasestorage.app',
    measurementId: 'G-8L7D4CZJMV',
  );
}
